import { Music, Code, Gamepad } from 'lucide-react';

export const events = [
    {
        id: 1,
        title: "Groove Up",
        category: "cultural",
        date: "2025-02-19",
        time: "12:00 PM - 6:00 PM",
        location: "UIET, Chandigarh",
        description: `Get ready for Goonj 2025 and its most exhilarating event of the year – the Inter-College Dance Competition! 🎉Bring your energy, creativity, and passion for dance to the stage.`,
        prizePool: "₹10,000+",
        teamSize: "2+ members",
        registrationFee: "₹2500/- per team",
        image: "/events/new/groove_up_template.jpg",
        register: "",
        brochure: "",
        icon: Music
    },
    {
        id: 2,
        title: "Bhangra Competition",
        category: "cultural",
        date: "2025-02-19",
        time: "5:00 PM - 10:00 PM",
        location: "UIET, Chandigarh",
        description: "Imagine this: the sound of the dhol filling the air, vibrant moves lighting up the stage, and the crowd cheering for every step. It’s not just a competition; it’s a celebration of who we are—our culture. ",
        prizePool: "₹10,000+",
        teamSize: "2+ members",
        registrationFee: "₹3000 per team",
        image: "/events/new/bhangra_template.jpg",
        register: "",
        brochure: "",
        icon: Music
    },
    {
        id: 3,
        title: "Nukkad Natak ",
        category: "cultural",
        date: "2024-02-19",
        time: "11:00 AM - 2:00 PM",
        location: "UIET, Chandigarh",
        description: "This is your chance to step into the soul-stirring world of street theatre, where words are powerful, emotions are raw, and every performance has the power to inspire change.",
        prizePool: "₹10,000+",
        teamSize: "2+ members",
        registrationFee: "₹2500 per team",
        image: "/events/new/nukkad_natak_template.jpg",
        register: "",
        brochure: "",
        icon: Music
    },
    {
        id: 4,
        title: "Technovate",
        category: "technical",
        date: "2024-02-19",
        time: "6:00 PM Onwards",
        location: "UIET, Chandigarh",
        description: "Are you ready to reach for the stars and unlock the mysteries of the cosmos? UIET Chandigarh presents TECHNOVATE’25, a thrilling 24-hour hackathon powered by the GDGC Club!",
        prizePool: "₹20,000+",
        teamSize: "2-5 members",
        registrationFee: "₹300 per team",
        image: "/events/new/Technovate.jpg",
        register: "",
        brochure: "",
        icon: Code
    },
    {
        id: 5,
        title: "Arduino Coding Challenge",
        category: "technical",
        date: "2024-02-20",
        time: "2:00 PM Onwards",
        location: "UIET, Chandigarh",
        description: "Test Your Coding & Hardware Skills in the Arduino Coding Challenge! In this exciting event, students will be given a problem to solve and must code an Arduino project that will be provided to them",
        prizePool: "₹3,000+",
        teamSize: "1-2 members",
        registrationFee: "₹100 per team",
        image: "/events/new/arduino_coding_challenge.jpg",
        brochure:"https://drive.google.com/file/d/1Di1gC0xPoM2KP1Um_R-fqn72odOuMq1S/view?usp=sharing",
        register: "https://docs.google.com/forms/d/e/1FAIpQLSexo0475_dzY_2F0klLnLCRags5Lm9M2FIGy4DTICD574Wj1w/viewform",
        icon: Code
    },
    {
        id: 6,
        title: "Tech Got Talent",
        category: "technical",
        date: "2024-02-21",
        time: "11:00 AM Onwards",
        location: "UIET, Chandigarh",
        description: "Ready to showcase your tech skills? Sign up now for Tech Got Talent, where you can present your software or hardware projects and compete for amazing awards!",
        prizePool: "₹4,000+",
        teamSize: "1-4 members",
        registrationFee: "₹100 per team",
        image: "/events/new/tech_got_talent.jpg",
        brochure: "https://drive.google.com/file/d/1FbJvHzODQP1p69dOBbtaG26mjuLPDzx7/view?usp=sharing",
        register: "https://docs.google.com/forms/d/e/1FAIpQLSelXYg-hfdMPOjzVOhHIoE4sPKhwW0Yw0tKRKSvHvJVClCkdQ/viewform?usp=sharing",
        icon: Code
    },
];
