import { Music, Code, Gamepad } from 'lucide-react';

export const events = [
    {
        id: 1,
        title: "Groove Up",
        category: "cultural",
        date: "2025-02-19",
        time: "12:00 PM - 6:00 PM",
        location: "UIET, Chandigarh",
        description: `Get ready for Goonj 2025 and its most exhilarating event of the year – the Inter-College Dance Competition! 🎉Bring your energy, creativity, and passion for dance to the stage.`,
        prizePool: "₹10,000+",
        teamSize: "2+ members",
        registrationFee: "₹2500/- per team",
        image: "/events/new/groove_up_template.jpg",
        register: "https://forms.gle/vGJAYb1RKyJLbB5Y9",
        brochure: "",
        rules: [
            "Each team must consist of at least three members.",
            "Participants are encouraged to showcase a variety of dance styles.",
            "The judges' decisions are final and binding."
        ],
        icon: Music
    },
    {
        id: 2,
        title: "Bhangra Competition",
        category: "cultural",
        date: "2025-02-19",
        time: "5:00 PM - 10:00 PM",
        location: "UIET, Chandigarh",
        description: "Imagine this: the sound of the dhol filling the air, vibrant moves lighting up the stage, and the crowd cheering for every step. It’s not just a competition; it’s a celebration of who we are—our culture. ",
        prizePool: "₹10,000+",
        teamSize: "2+ members",
        registrationFee: "₹3000 per team",
        image: "/events/new/bhangra_template.jpg",
        register: "https://tr.ee/kjpixmVTYP",
        brochure: "",
        rules: [
            "Each team must consist of at least three members.",
            "Teams must adhere to traditional Bhangra themes and movements while incorporating creative elements.",
            "Use of traditional Bhangra props, such as dhols, saaps, chimtas, or khundas, is allowed and encouraged.",
            "The judges' decisions are final and binding."
        ],
        icon: Music
    },
    {
        id: 3,
        title: "Nukkad Natak ",
        category: "cultural",
        date: "2024-02-19",
        time: "11:00 AM - 2:00 PM",
        location: "UIET, Chandigarh",
        description: "This is your chance to step into the soul-stirring world of street theatre, where words are powerful, emotions are raw, and every performance has the power to inspire change.",
        prizePool: "₹10,000+",
        teamSize: "2+ members",
        registrationFee: "₹2500 per team",
        image: "/events/new/nukkad_natak_template.jpg",
        register: "https://forms.gle/ZobuVN6oasjjUMpbA",
        brochure: "",
        rules: [
            "Performances can be in Hindi, English or a mix of both.",
            "Vulgarity or offensive content is strictly prohibited.",
            "Teams may use handheld props and costumes.",
            "Performances must adapt to an open and informal setting.",
        ],
        icon: Music
    },
    {
        id: 4,
        title: "Technovate",
        category: "technical",
        date: "2024-02-19",
        time: "6:00 PM Onwards",
        location: "UIET, Chandigarh",
        description: "Are you ready to reach for the stars and unlock the mysteries of the cosmos? UIET Chandigarh presents TECHNOVATE’25, a thrilling 24-hour hackathon powered by the GDGC Club!",
        prizePool: "₹20,000+",
        teamSize: "2-5 members",
        registrationFee: "₹300 per team",
        image: "/events/new/Technovate.jpg",
        register: "",
        brochure: "",
        rules: [
            "Teams: 2-5 members per team.",
            "Bring your own devices and chargers.",
            "Code of conduct must be adhered to.",
            "Submissions will be judged based on creativity, functionality, and overall execution.",
        ],
        icon: Code
    },
    {
        id: 5,
        title: "Arduino Coding Challenge",
        category: "technical",
        date: "2024-02-20",
        time: "2:00 PM Onwards",
        location: "UIET, Chandigarh",
        description: "Test Your Coding & Hardware Skills in the Arduino Coding Challenge! In this exciting event, students will be given a problem to solve and must code an Arduino project that will be provided to them",
        prizePool: "₹3,000+",
        teamSize: "1-2 members",
        registrationFee: "₹100 per team",
        image: "/events/new/arduino_coding_challenge.jpg",
        brochure:"arduino_coding_challenge_brochure.pdf",
        register: "https://forms.gle/kTr6HvFDoTZoARFh9",
        // rules: [
        //     "Teams: 1-2 members per team.",
        //     "Bring your own devices and chargers.",
        //     "Code of conduct must be adhered to.",
        //     "Submissions will be judged based on creativity, functionality, and overall execution.",
        // ],
        icon: Code
    },
    {
        id: 6,
        title: "Tech Got Talent",
        category: "technical",
        date: "2024-02-21",
        time: "11:00 AM Onwards",
        location: "UIET, Chandigarh",
        description: "Ready to showcase your tech skills? Sign up now for Tech Got Talent, where you can present your software or hardware projects and compete for amazing awards!",
        prizePool: "₹4,000+",
        teamSize: "1-4 members",
        registrationFee: "₹100 per team",
        image: "/events/new/tech_got_talent.jpg",
        brochure: "tech_got_talent_brochure.pdf",
        register: "https://forms.gle/caGEJDjVkMXT9oNi9",
        // rules: [
        //     "Teams: 1-4 members per team.",
        //     "Bring your own devices and chargers.",
        //     "Code of conduct must be adhered to.",
        //     "Submissions will be judged based on creativity, functionality, and overall execution.",
        // ],
        icon: Code
    },
    {
        id: 7,
        title: "Path Fury",
        category: "technical",
        date: "2024-02-20",
        time: "11:00 AM Onwards",
        location: "UIET, Chandigarh",
        description: "Put your engineering precision to the test at Goonj 2025! Design and program a line-following bot capable of navigating a complex track with sharp turns, intersections, and unexpected challenges.",
        prizePool: "₹4,000+",
        teamSize: "2-5 members",
        registrationFee: "₹299 per team",
        image: "/events/new/tech_got_talent.jpg",
        brochure: "tech_got_talent_brochure.pdf",
        register: "https://forms.gle/T6aRKmFeKaK7Qzvb8",
        // rules: [
        //     "Teams: 1-4 members per team.",
        //     "Bring your own devices and chargers.",
        //     "Code of conduct must be adhered to.",
        //     "Submissions will be judged based on creativity, functionality, and overall execution.",
        // ],
        icon: Code
    },
    {
        id: 8,
        title: "Cad Design Showdown",
        category: "technical",
        date: "2024-02-21",
        time: "11:00 AM Onwards",
        location: "UIET, Chandigarh",
        description: "Test your CAD skills in this exciting competition at Goonj, our annual techno-cultural fest. Create innovative designs and compete for amazing prizes.",
        prizePool: "₹2000",
        teamSize: "Individual",
        registrationFee: "₹49 per Member",
        image: "/events/new/tech_got_talent.jpg",
        brochure: "tech_got_talent_brochure.pdf",
        register: "https://forms.gle/oiWBjFRcedsLH65B8",
        // rules: [
        //     "Teams: 1-4 members per team.",
        //     "Bring your own devices and chargers.",
        //     "Code of conduct must be adhered to.",
        //     "Submissions will be judged based on creativity, functionality, and overall execution.",
        // ],
        icon: Code
    },
    {
        id: 9,
        title: "Aquqventure",
        category: "technical",
        date: "2024-02-19",
        time: "11:00 AM Onwards",
        location: "UIET, Chandigarh",
        description: "Experience the perfect blend of science and excitement at Goonj 2025 with the Water Rocket event. Design, build, and launch your own water rocket, aiming for maximum altitude and precision.",
        prizePool: "₹3,000+",
        teamSize: "3-5 members",
        registrationFee: "₹199 per team",
        image: "/events/new/tech_got_talent.jpg",
        brochure: "tech_got_talent_brochure.pdf",
        register: "https://forms.gle/BRsYsJCyekjPo5bd9",
        // rules: [
        //     "Teams: 1-4 members per team.",
        //     "Bring your own devices and chargers.",
        //     "Code of conduct must be adhered to.",
        //     "Submissions will be judged based on creativity, functionality, and overall execution.",
        // ],
        icon: Code
    },
    {
        id: 10,
        title: "UI/UX Unleashed",
        category: "technical",
        date: "2024-02-20",
        time: "11:00 AM Onwards",
        location: "UIET, Chandigarh",
        description: "Design The Future, Shape The Experience! the Ultimate UI/UX Competition !",
        prizePool: "Win Exciting Prices",
        teamSize: "Individual",
        registrationFee: "₹50 per Member",
        image: "/events/new/tech_got_talent.jpg",
        brochure: "tech_got_talent_brochure.pdf",
        register: "https://forms.gle/GB69q5EwAwfzfMJy6",
        // rules: [
        //     "Teams: 1-4 members per team.",
        //     "Bring your own devices and chargers.",
        //     "Code of conduct must be adhered to.",
        //     "Submissions will be judged based on creativity, functionality, and overall execution.",
        // ],
        icon: Code
    },
    {
        id: 11,
        title: "Fifa League",
        category: "Gaming",
        date: "2024-02-19",
        time: "11:00 AM Onwards",
        location: "UIET, Chandigarh",
        description: "Design The Future, Shape The Experience! the Ultimate UI/UX Competition !",
        prizePool: "₹2,000+",
        teamSize: "Individual",
        registrationFee: "₹50 per Member",
        image: "/events/new/tech_got_talent.jpg",
        brochure: "tech_got_talent_brochure.pdf",
        register: "https://forms.gle/cdJPn7MJd1KWH5E76",
        // rules: [
        //     "Teams: 1-4 members per team.",
        //     "Bring your own devices and chargers.",
        //     "Code of conduct must be adhered to.",
        //     "Submissions will be judged based on creativity, functionality, and overall execution.",
        // ],
        icon: Code
    },
    {
        id: 12,
        title: "Design Jam",
        category: "technical",
        date: "2024-02-19",
        time: "11:00 AM Onwards",
        location: "UIET, Chandigarh",
        description: " Step into the world of Blockchain and create breathtaking generative AI art!",
        prizePool: "Win Exciting Prices",
        teamSize: "Individual",
        registrationFee: "Free Of Cost",
        image: "/events/new/tech_got_talent.jpg",
        brochure: "tech_got_talent_brochure.pdf",
        register: "https://forms.gle/nWvQaPx1JGg2BhMN8",
        // rules: [
        //     "Teams: 1-4 members per team.",
        //     "Bring your own devices and chargers.",
        //     "Code of conduct must be adhered to.",
        //     "Submissions will be judged based on creativity, functionality, and overall execution.",
        // ],
        icon: Code
    },
    {
        id: 13,
        title: "Cryptic Hunt",
        category: "technical",
        date: "2024-02-20",
        time: "11:00 AM Onwards",
        location: "UIET, Chandigarh",
        description: "Navigate through mazes and solve mind bending riddles using your coding skills!",
        prizePool: "Win Exciting Prices",
        teamSize: "Individual",
        registrationFee: "₹50 per Member",
        image: "/events/new/tech_got_talent.jpg",
        brochure: "tech_got_talent_brochure.pdf",
        register: "https://forms.gle/MBtGzpncbehWnRxq7",
        // rules: [
        //     "Teams: 1-4 members per team.",
        //     "Bring your own devices and chargers.",
        //     "Code of conduct must be adhered to.",
        //     "Submissions will be judged based on creativity, functionality, and overall execution.",
        // ],
        icon: Code
    },
    {
        id: 14,
        title: "Pair Panic",
        category: "technical",
        date: "2024-02-20",
        time: "11:00 AM Onwards",
        location: "UIET, Chandigarh",
        description: " One person types the code blindfolded The other? Your guiding light who can see the screen but can't touch the keyboard",
        prizePool: "Win Exciting Prices",
        teamSize: "2 Members",
        registrationFee: "Free Of Cost",
        image: "/events/new/tech_got_talent.jpg",
        brochure: "tech_got_talent_brochure.pdf",
        register: "https://forms.gle/2xum23mrTUzvzqXn9",
        // rules: [
        //     "Teams: 1-4 members per team.",
        //     "Bring your own devices and chargers.",
        //     "Code of conduct must be adhered to.",
        //     "Submissions will be judged based on creativity, functionality, and overall execution.",
        // ],
        icon: Code
    },
    {
        id: 15,
        title: "Quiz Show",
        category: "Fun",
        date: "2024-02-20",
        time: "11:00 AM Onwards",
        location: "UIET, Chandigarh",
        description: "Programming Club UIET presents an exciting Technical Quiz Game Show! Test your tech knowledge across a quiz inspired by a game show format.",
        prizePool: "₹3,000+",
        teamSize: "Individual",
        registrationFee: "₹100 per Member",
        image: "/events/new/tech_got_talent.jpg",
        brochure: "tech_got_talent_brochure.pdf",
        register: "https://forms.gle/V4KfwKZEdFnreBLp6",
        // rules: [
        //     "Teams: 1-4 members per team.",
        //     "Bring your own devices and chargers.",
        //     "Code of conduct must be adhered to.",
        //     "Submissions will be judged based on creativity, functionality, and overall execution.",
        // ],
        icon: Code
    },
    {
        id: 16,
        title: "Mr And Mrs Goonj",
        category: "cultural",
        date: "2025-02-19",
        time: "12:00 PM - 6:00 PM",
        location: "UIET, Chandigarh",
        description: "Step into the spotlight and own the runway like never before! This isn’t just a fashion show—it’s a celebration of confidence, creativity, and charisma. Whether you're a trendsetter, a bold rule-breaker, or the epitome of timeless elegance, this is your moment to shine.",
        prizePool: "₹3,000+",
        teamSize: "Individual",
        registrationFee: "₹200 Per Person",
        image: "/events/new/groove_up_template.jpg",
        register: "https://docs.google.com/forms/d/e/1FAIpQLSeXPkDBlossHGmN75OcjvZmu1fwT9LrZVSv4X6Vccm5qWvU2A/viewform",
        brochure: "",
        // rules: [
        //     "Each team must consist of at least three members.",
        //     "Participants are encouraged to showcase a variety of dance styles.",
        //     "The judges' decisions are final and binding."
        // ],
        icon: Music
    },
    {
        id: 17,
        title: "Turncoat",
        category: "cultural",
        date: "2025-02-20",
        time: "12:00 PM - 6:00 PM",
        location: "UIET, Chandigarh",
        description: `Welcome to the Turncoat Debate at Goonj 2025! This is your chance to showcase your argumentation skills, quick thinking, and adaptability in a high-energy format where you'll debate both for and against the topic.`,
        prizePool: "₹1000+",
        teamSize: "Individual",
        registrationFee: "₹50 Per Person",
        image: "/events/new/groove_up_template.jpg",
        register: "https://docs.google.com/forms/d/e/1FAIpQLSdxbOqvYKThJt41HyslsmNZUoTn5XWIH874Ps0BoG602FULjg/viewform",
        brochure: "",
        // rules: [
        //     "Each team must consist of at least three members.",
        //     "Participants are encouraged to showcase a variety of dance styles.",
        //     "The judges' decisions are final and binding."
        // ],
        icon: Music
    },
    {
        id: 18,
        title: "Suron Ka Karwa",
        category: "cultural",
        date: "2025-02-19",
        time: "12:00 PM - 6:00 PM",
        location: "UIET, Chandigarh",
        description: "Unleash your talent at Suroon Ka Karvan, the Open Mic Competition at Goonj 2025! Whether you're a singer, poet, storyteller, or musician, this is your stage to shine. Fill out the form to register and let your voice be heard!",
        prizePool: "Win Exciting Prices",
        teamSize: "Individual",
        registrationFee: "Free Of Cost",
        image: "/events/new/groove_up_template.jpg",
        register: "https://docs.google.com/forms/d/e/1FAIpQLSexwhcjqCSH2kkSZJFrwhMgFsPw6W0hiErLshCQHcj2dd53ZA/viewform",
        brochure: "",
        // rules: [
        //     "Each team must consist of at least three members.",
        //     "Participants are encouraged to showcase a variety of dance styles.",
        //     "The judges' decisions are final and binding."
        // ],
        icon: Music
    },
    {
        id: 19,
        title: "Charcoal Challenge",
        category: "cultural",
        date: "2025-02-19",
        time: "12:00 PM - 2:00 PM",
        location: "UIET, Chandigarh",
        description: `Unleash your creativity with just pencils, graphite, and charcoal in this intense sketching competition!`,
        prizePool: "₹750",
        teamSize: "Individual",
        registrationFee: "₹60/- Per Person",
        image: "/events/new/groove_up_template.jpg",
        register: "https://docs.google.com/forms/d/e/1FAIpQLSeH-VS39C-aFQqZ2lPKFS7MqOUerXz8qbGgtPQ9QAj6rOC0zQ/viewform",
        brochure: "",
        // rules: [
        //     "Each team must consist of at least three members.",
        //     "Participants are encouraged to showcase a variety of dance styles.",
        //     "The judges' decisions are final and binding."
        // ],
        icon: Music
    },
    {
        id: 20,
        title: "Pocket Sized",
        category: "cultural",
        date: "2025-02-20",
        time: "12:00 PM - 1:30 PM",
        location: "UIET, Chandigarh",
        description: `Unleash your creativity on a 12x12-inch handkerchief! With an on-the-spot theme and just 90 minutes, can you turn fabric into a masterpiece?`,
        prizePool: "₹2500",
        teamSize: "Individual",
        registrationFee: "₹75/- Per Person",
        image: "/events/new/groove_up_template.jpg",
        register: "https://docs.google.com/forms/d/e/1FAIpQLSc-4RhHKbPZdwsm9UAnnRoRhWuL2qIbVg4WZRq7bUM2qvk7JA/viewform",
        brochure: "",
        // rules: [
        //     "Each team must consist of at least three members.",
        //     "Participants are encouraged to showcase a variety of dance styles.",
        //     "The judges' decisions are final and binding."
        // ],
        icon: Music
    },
    {
        id: 21,
        title: "Duet Dance Competition",
        category: "cultural",
        date: "2025-02-20",
        time: "12:00 PM - 2:00 PM",
        location: "UIET, Chandigarh",
        description: `Get ready to light up the stage with your partner at Goonj 2025's electrifying Duet Dance Competition! 🎉
Showcase your chemistry, coordination, and creativity as you dance in perfect harmony. Whether you're a dynamic duo or a soulful pairing, this is your moment to inspire, captivate, and mesmerize the audience with your synchronized steps and innovative choreography.`,
        prizePool: "₹1700",
        teamSize: "Individual",
        registrationFee: "₹250/- Per Team",
        image: "/events/new/groove_up_template.jpg",
        register: "https://docs.google.com/forms/d/e/1FAIpQLSdVkbQkJiY6R9nH7Z1F0v9L3aJaQr0eCBjQ4X-5TSbL56eQXw/viewform",
        brochure: "",
        // rules: [
        //     "Each team must consist of at least three members.",
        //     "Participants are encouraged to showcase a variety of dance styles.",
        //     "The judges' decisions are final and binding."
        // ],
        icon: Music
    },
    {
        id: 22,
        title: "Solo Dance Competition",
        category: "cultural",
        date: "2025-02-20",
        time: "12:00 PM - 2:00 PM",
        location: "UIET, Chandigarh",
        description: `Get ready for Goonj 2025 and its most exhilarating event of the year – the Inter-College Dance Competition! 🎉Bring your energy, creativity, and passion for dance to the stage.`,
        prizePool: "₹1000",
        teamSize: "Individual",
        registrationFee: "₹100/- Per Person",
        image: "/events/new/groove_up_template.jpg",
        register: "https://forms.gle/vGJAYb1RKyJLbB5Y9",
        brochure: "",
        // rules: [
        //     "Each team must consist of at least three members.",
        //     "Participants are encouraged to showcase a variety of dance styles.",
        //     "The judges' decisions are final and binding."
        // ],
        icon: Music
    },
    {
        id: 23,
        title: "Bhangra Wars",
        category: "cultural",
        date: "2025-02-19",
        time: "12:00 PM - 2:00 PM",
        location: "UIET, Chandigarh",
        description: `The dhols are ready, the beats are calling, and the stage is set for Bhangra Wars 2025 at Goonj 2025! 💃🕺
This isn’t just a competition—it’s a celebration of energy, rhythm, and culture. Get ready to witness jaw-dropping performances as dancers pour their hearts into every move, matching their passion with the infectious beats of Bhangra. 🎶✨`,
        prizePool: "₹1000",
        teamSize: "2 members",
        registrationFee: "₹100/- Per Team",
        image: "/events/new/groove_up_template.jpg",
        register: "https://docs.google.com/forms/d/e/1FAIpQLScr2tlO6eKANKcsncYnBr4eemA7TMZHO8HUiACWZs-gb76TDw/viewform",
        brochure: "",
        // rules: [
        //     "Each team must consist of at least three members.",
        //     "Participants are encouraged to showcase a variety of dance styles.",
        //     "The judges' decisions are final and binding."
        // ],
        icon: Music
    },
    {
        id: 24,
        title: "Monoact",
        category: "cultural",
        date: "2025-02-19",
        time: "12:00 PM - 2:00 PM",
        location: "UIET, Chandigarh",
        description: `Step into the spotlight and let your unmatched talent and imagination take center stage. This is your moment to captivate every heart and soul in the audience as you embody emotions, tell compelling stories, and deliver a performance that will leave everyone spellbound. 💫 Whether you’re an experienced performer or new to the art, this is your opportunity to dazzle, inspire, and make your mark!`,
        prizePool: "₹1000+",
        teamSize: "Individual",
        registrationFee: "₹50/- Per Person",
        image: "/events/new/groove_up_template.jpg",
        register: "https://docs.google.com/forms/d/e/1FAIpQLSdU8nJlQYDKqYJKuk2bkoEs9_aY6PXwuNDnoZP3wWr9634Tcg/viewform",
        brochure: "",
        // rules: [
        //     "Each team must consist of at least three members.",
        //     "Participants are encouraged to showcase a variety of dance styles.",
        //     "The judges' decisions are final and binding."
        // ],
        icon: Music
    },
    
];
